# Author: Leonardo Salicari (@loscati)
# Date: 6/2025

name: Deploy Bridget-based site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo (Extended)
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build site
        run: hugo --source impressioni --minify --logLevel debug --printPathWarnings

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.SECRET }}
          publish_dir: ./impressioni/public  # NOTE: Hugo dump the generate .html here
